import BreadCrumbs from "../../../components/BreadCrumbs";
import Spinner from "../../../components/Spinner";
import { CategoryList } from "../../../partials/Category";

async function getDishes(id: string) {
  // request to the server
  return [
    {
      _id: "63f3d89f24e1d071ed3d079a",
      name: "Козацька",
      imagePath: "/static/dishes/pizza/cossack.webp",
      weight: 545,
      price: 203,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "cossack",
      ingredients: [
        "мисливські ковбаски",
        "шинка",
        "чилі",
        "огірки мариновані",
        "соус томатний",
        "салямі",
        "цибуля",
        "сир моцарела",
      ],
    },
    {
      _id: "63f3da5824e1d071ed3d07b2",
      name: "Фелічіта",
      imagePath: "/static/dishes/pizza/felicita.webp",
      weight: 530,
      price: 185,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "felicita",
      ingredients: [
        "бекон",
        "куряче філе",
        "соус томатний",
        "сир моцарела",
        "гриби",
      ],
    },
    {
      _id: "63f3d93224e1d071ed3d07a2",
      name: "Прошуто Фунгі",
      imagePath: "/static/dishes/pizza/proshuto_fungi.webp",
      weight: 430,
      price: 165,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "proshuto-fungi",
      ingredients: ["шинка", "гриби", "соус томатний", "сир моцарела"],
    },
    {
      _id: "63f3da2d24e1d071ed3d07b0",
      name: "Песто",
      imagePath: "/static/dishes/pizza/pesto.webp",
      weight: 460,
      price: 195,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "pesto",
      ingredients: [
        "соус песто",
        "бекон",
        "перець болгарський",
        "сир моцарела",
        "шинка",
        "соус томатний",
      ],
    },
    {
      _id: "63f3daa724e1d071ed3d07b6",
      name: "Чізбургер",
      imagePath: "/static/dishes/pizza/cheeseburger.webp",
      weight: 540,
      price: 180,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "cheeseburger",
      ingredients: [
        "сир моцарела",
        "соус томатний",
        "огірки мариновані",
        "цибуля",
        "бекон",
        "помідори",
        "гірчиця",
      ],
    },
    {
      _id: "63f3d88324e1d071ed3d0798",
      name: "Салямі",
      imagePath: "/static/dishes/pizza/salami.webp",
      weight: 400,
      price: 164,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "salami",
      ingredients: ["салямі", "основа", "соус томатний", "сир моцарела"],
    },
    {
      _id: "63f3d8bb24e1d071ed3d079c",
      name: "Спайсі курка",
      imagePath: "/static/dishes/pizza/spicy_chicken.webp",
      weight: 480,
      price: 173,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "spicy-chicken",
      ingredients: [
        "сир моцарела",
        "кукурудза",
        "куряче філе",
        "соус солодкий чилі",
        "соус томатний",
      ],
    },
    {
      _id: "63f3d9ce24e1d071ed3d07aa",
      name: "Корнелія",
      imagePath: "/static/dishes/pizza/cornelia.webp",
      weight: 450,
      price: 165,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "cornelia",
      ingredients: ["сир моцарела", "салямі", "кукурудза", "сир вершковий"],
    },
    {
      _id: "63f3d95e24e1d071ed3d07a4",
      name: "4 Сезони",
      imagePath: "/static/dishes/pizza/4_seasons.webp",
      weight: 500,
      price: 195,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "4-seasons",
      ingredients: [
        "сир моцарела",
        "гриби",
        "кукурудза",
        "шинка",
        "соус томатний",
        "пепероні",
      ],
    },
    {
      _id: "63f3da8424e1d071ed3d07b4",
      name: "Цезар",
      imagePath: "/static/dishes/pizza/caesar.webp",
      weight: 480,
      price: 210,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "caesar",
      ingredients: [
        "перепелині яйця",
        "сир пармезан",
        "соус томатний",
        "сир моцарела",
        "сезонний салат",
        "помідори чері",
        "куряче філе",
      ],
    },
    {
      _id: "63f3d8e524e1d071ed3d079e",
      name: "Пепероні",
      imagePath: "/static/dishes/pizza/pepperoni.webp",
      weight: 410,
      price: 190,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "pepperoni",
      ingredients: ["сир моцарела", "пепероні", "соус томатний"],
    },
    {
      _id: "63f3d85124e1d071ed3d0795",
      name: "Капрічоза",
      imagePath: "/static/dishes/pizza/caprice.webp",
      weight: 550,
      price: 195,
      isNovelty: true,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "caprice",
      ingredients: [
        "гриби",
        "сир моцарела",
        "салямі",
        "соус томатний",
        "помідори",
        "шинка",
      ],
    },
    {
      _id: "63f3da0c24e1d071ed3d07ae",
      name: "Мексиканська",
      imagePath: "/static/dishes/pizza/mexican.webp",
      weight: 510,
      price: 205,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "mexican",
      ingredients: [
        "бекон",
        "пепероні",
        "соус томатний",
        "гриби",
        "перець халапеньо",
        "сир моцарела",
      ],
    },
    {
      _id: "63f3d9ae24e1d071ed3d07a8",
      name: "Карлеоне",
      imagePath: "/static/dishes/pizza/corleone.webp",
      weight: 450,
      price: 195,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "corleone",
      ingredients: ["соус томатний", "пепероні", "сир моцарела", "сир дор блю"],
    },
    {
      _id: "63f3d91d24e1d071ed3d07a0",
      name: "Техас",
      imagePath: "/static/dishes/pizza/texas.webp",
      weight: 490,
      price: 200,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "texas",
      ingredients: [
        "куряче філе",
        "шинка",
        "соус томатний",
        "сир моцарела",
        "помідори",
        "соус солодкий чилі",
      ],
    },
    {
      _id: "63f3d97f24e1d071ed3d07a6",
      name: "Базиліца",
      imagePath: "/static/dishes/pizza/basilica.webp",
      weight: 420,
      price: 180,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "basilica",
      ingredients: [
        "соус песто",
        "маслини",
        "соус вершковий",
        "сир моцарела",
        "сир фета",
        "помідори",
      ],
    },
    {
      _id: "63f3d9f024e1d071ed3d07ac",
      name: "Маргарита",
      imagePath: "/static/dishes/pizza/margarita.webp",
      weight: 450,
      price: 135,
      isNovelty: false,
      dishCategory: {
        _id: "63f3d0cf24e1d071ed3d074f",
        name: "Піца",
      },
      __v: 0,
      slug: "margarita",
      ingredients: ["соус томатний", "сир моцарела", "помідори"],
    },
  ];
}

const Category = async ({ params }: { params: { id: string } }) => {
  const dishes = await getDishes(params.id);

  return (
    <main className="main">
      {/* <BreadCrumbs
        pathes={[
          { path: "/", name: "Головна" },
          { path: "/category/", name: dishes[0]?.dishCategory.name },
        ]}
      /> */}
      <CategoryList dishes={dishes} />
    </main>
  );
};

export default Category;
